modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"

[[dependencies.sourceofmystery]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.8,5)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="sourceofmystery"
version="1.0.0"
displayName="Source Of Mystery"
description='''
SourceOfMystery Mod - Mystery and Magic Experience
'''
